#!/usr/bin/env bash

#sudo -v

$(pwd)/scripts/before_install.sh
make
$(pwd)/scripts/install.sh

if [[ "$OSTYPE" == "linux"* ]]; then
#screen -S 2 /usr/sbin/./iftop
$(pwd)/scripts/before_script.sh
$(pwd)/scripts/script.sh
elif [[ "$OSTYPE" == "darwin"* ]]; then
#screen -S 2 sudo /usr/local/sbin/./iftop
$(pwd)/scripts/before_script.sh
$(pwd)/scripts/script.sh
elif [[ "$OSTYPE" == "cygwin" ]]; then
echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "msys" ]]; then
echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "win32" ]]; then
echo TODO add support for $OSTYPE
elif [[ "$OSTYPE" == "freebsd"* ]]; then
echo TODO add support for $OSTYPE
else
echo TODO add support for $OSTYPE
fi

